### ISSUE TITLE
if you try to log in with github without an account, it errors

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#230]
From https://github.com/mozilla/standup/issues/219#issuecomment-248635572

@kanru said:

> I tried to login with Github directly, got Internal Server Error 

We should follow up on this before pushing out v2.

**Comment by pmac** [comment]
I can't reproduce this. We've now added Sentry error handling to the staging app. @kanru would you mind trying again?

**Comment by willkg** [comment]
He might not be able to trigger it again since I'm pretty sure he's got a valid github auth account now.

Oops--that quote is totally out of context. The full context is this:

> I tried to login with Github directly, got Internal Server Error
> Successfully login with Persona and convert to Github auth
> Logout and login again with Github auth

I'll try it out. I don't have a github account on the new server, yet.

**Comment by willkg** [comment]
I couldn't reproduce it, either. However, I did find the relevant error in the logs:

```
2016-09-21T14:39:36.839604+00:00 app[web.1]: [2016-09-21 14:39:36 +0000] [14] [ERROR] Error handling request /complete/github/?code=73558e8a021a5f49304d&redirect_state=wl2TvwkMiUjWjWUn80J84abYZHmDBPZ0&state=wl2TvwkMiUjWjWUn80J84abYZHmDBPZ0
2016-09-21T14:39:36.839610+00:00 app[web.1]: Traceback (most recent call last):
2016-09-21T14:39:36.839611+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
2016-09-21T14:39:36.839612+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2016-09-21T14:39:36.839613+00:00 app[web.1]: psycopg2.IntegrityError: duplicate key value violates unique constraint "user_github_handle_key"
2016-09-21T14:39:36.839616+00:00 app[web.1]: DETAIL:  Key (github_handle)=(kanru) already exists.
2016-09-21T14:39:36.839618+00:00 app[web.1]: 
2016-09-21T14:39:36.839617+00:00 app[web.1]: 
2016-09-21T14:39:36.839619+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2016-09-21T14:39:36.839620+00:00 app[web.1]: 
2016-09-21T14:39:36.839620+00:00 app[web.1]: Traceback (most recent call last):
2016-09-21T14:39:36.839621+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 132, in get_response
2016-09-21T14:39:36.839621+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-09-21T14:39:36.839623+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
2016-09-21T14:39:36.839624+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2016-09-21T14:39:36.839624+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2016-09-21T14:39:36.839625+00:00 app[web.1]:     return view_func(*args, **kwargs)
2016-09-21T14:39:36.839625+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/apps/django_app/utils.py", line 51, in wrapper
2016-09-21T14:39:36.839626+00:00 app[web.1]:     return func(request, backend, *args, **kwargs)
2016-09-21T14:39:36.839627+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/apps/django_app/views.py", line 28, in complete
2016-09-21T14:39:36.839628+00:00 app[web.1]:     redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
2016-09-21T14:39:36.839629+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/actions.py", line 44, in do_complete
2016-09-21T14:39:36.839629+00:00 app[web.1]:     user = backend.complete(user=user, *args, **kwargs)
2016-09-21T14:39:36.839630+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/backends/base.py", line 41, in complete
2016-09-21T14:39:36.839630+00:00 app[web.1]:     return self.auth_complete(*args, **kwargs)
2016-09-21T14:39:36.839631+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/utils.py", line 246, in wrapper
2016-09-21T14:39:36.839632+00:00 app[web.1]:     return func(*args, **kwargs)
2016-09-21T14:39:36.839632+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/backends/oauth.py", line 397, in auth_complete
2016-09-21T14:39:36.839633+00:00 app[web.1]:     *args, **kwargs)
2016-09-21T14:39:36.839634+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/utils.py", line 246, in wrapper
2016-09-21T14:39:36.839634+00:00 app[web.1]:     return func(*args, **kwargs)
2016-09-21T14:39:36.839635+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/backends/oauth.py", line 408, in do_auth
2016-09-21T14:39:36.839635+00:00 app[web.1]:     return self.strategy.authenticate(*args, **kwargs)
2016-09-21T14:39:36.839636+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/strategies/django_strategy.py", line 96, in authenticate
2016-09-21T14:39:36.839637+00:00 app[web.1]:     return authenticate(*args, **kwargs)
2016-09-21T14:39:36.839637+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 74, in authenticate
2016-09-21T14:39:36.839638+00:00 app[web.1]:     user = backend.authenticate(**credentials)
2016-09-21T14:39:36.839639+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/backends/base.py", line 82, in authenticate
2016-09-21T14:39:36.839639+00:00 app[web.1]:     return self.pipeline(pipeline, *args, **kwargs)
2016-09-21T14:39:36.839640+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/backends/base.py", line 85, in pipeline
2016-09-21T14:39:36.839640+00:00 app[web.1]:     out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
2016-09-21T14:39:36.839641+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/social/backends/base.py", line 112, in run_pipeline
2016-09-21T14:39:36.839642+00:00 app[web.1]:     result = func(*args, **out) or {}
2016-09-21T14:39:36.839642+00:00 app[web.1]:   File "/app/standup/status/auth.py", line 22, in create_user_profile
2016-09-21T14:39:36.839643+00:00 app[web.1]:     profile.save()
2016-09-21T14:39:36.839644+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 734, in save
2016-09-21T14:39:36.839644+00:00 app[web.1]:     force_update=force_update, update_fields=update_fields)
2016-09-21T14:39:36.839645+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 762, in save_base
2016-09-21T14:39:36.839646+00:00 app[web.1]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
2016-09-21T14:39:36.839646+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 827, in _save_table
2016-09-21T14:39:36.839647+00:00 app[web.1]:     forced_update)
2016-09-21T14:39:36.839648+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 877, in _do_update
2016-09-21T14:39:36.839648+00:00 app[web.1]:     return filtered._update(values) > 0
2016-09-21T14:39:36.839649+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 580, in _update
2016-09-21T14:39:36.839650+00:00 app[web.1]:     return query.get_compiler(self.db).execute_sql(CURSOR)
2016-09-21T14:39:36.839651+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
2016-09-21T14:39:36.839651+00:00 app[web.1]:     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
2016-09-21T14:39:36.840456+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
2016-09-21T14:39:36.840458+00:00 app[web.1]:     cursor.execute(sql, params)
2016-09-21T14:39:36.840458+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
2016-09-21T14:39:36.840459+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2016-09-21T14:39:36.840460+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 98, in __exit__
2016-09-21T14:39:36.840460+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
2016-09-21T14:39:36.840461+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
2016-09-21T14:39:36.840462+00:00 app[web.1]:     raise value.with_traceback(tb)
2016-09-21T14:39:36.840463+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
2016-09-21T14:39:36.840463+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2016-09-21T14:39:36.840464+00:00 app[web.1]: django.db.utils.IntegrityError: duplicate key value violates unique constraint "user_github_handle_key"
2016-09-21T14:39:36.840465+00:00 app[web.1]: DETAIL:  Key (github_handle)=(kanru) already exists.
2016-09-21T14:39:36.840465+00:00 app[web.1]: 
2016-09-21T14:39:36.840467+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2016-09-21T14:39:36.840466+00:00 app[web.1]: 
2016-09-21T14:39:36.840467+00:00 app[web.1]: 
2016-09-21T14:39:36.840468+00:00 app[web.1]: Traceback (most recent call last):
2016-09-21T14:39:36.840468+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 135, in handle
2016-09-21T14:39:36.840469+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2016-09-21T14:39:36.840470+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
2016-09-21T14:39:36.840470+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2016-09-21T14:39:36.840471+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
2016-09-21T14:39:36.840471+00:00 app[web.1]:     response = self.get_response(request)
2016-09-21T14:39:36.840472+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 218, in get_response
2016-09-21T14:39:36.840473+00:00 app[web.1]:     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
2016-09-21T14:39:36.840473+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 268, in handle_uncaught_exception
2016-09-21T14:39:36.840474+00:00 app[web.1]:     return callback(request, **param_dict)
2016-09-21T14:39:36.840475+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
2016-09-21T14:39:36.840475+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2016-09-21T14:39:36.840484+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/views/defaults.py", line 45, in server_error
2016-09-21T14:39:36.840484+00:00 app[web.1]:     return http.HttpResponseServerError(template.render())
2016-09-21T14:39:36.840485+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django_jinja/backend.py", line 105, in render
2016-09-21T14:39:36.840485+00:00 app[web.1]:     return self.template.render(context)
2016-09-21T14:39:36.840486+00:00 app[web.1]:     return self.environment.handle_exception(exc_info, True)
2016-09-21T14:39:36.840486+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 989, in render
2016-09-21T14:39:36.840487+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-09-21T14:39:36.840487+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 754, in handle_exception
2016-09-21T14:39:36.840488+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
2016-09-21T14:39:36.840489+00:00 app[web.1]:   File "/app/standup/status/jinja2/500.html", line 2, in top-level template code
2016-09-21T14:39:36.840488+00:00 app[web.1]:     raise value.with_traceback(tb)
2016-09-21T14:39:36.840489+00:00 app[web.1]:     {% set title = '500: Something went wrong...' %}
2016-09-21T14:39:36.840490+00:00 app[web.1]:   File "/app/standup/status/jinja2/base.html", line 6, in top-level template code
2016-09-21T14:39:36.840491+00:00 app[web.1]:     <title>{% block title %}{{ settings.SITE_TITLE }}{% endblock %}</title>
2016-09-21T14:39:36.840491+00:00 app[web.1]:   File "/app/standup/status/jinja2/base.html", line 6, in block "title"
2016-09-21T14:39:36.840492+00:00 app[web.1]:     <title>{% block title %}{{ settings.SITE_TITLE }}{% endblock %}</title>
2016-09-21T14:39:36.840493+00:00 app[web.1]:     return getattr(obj, attribute)
2016-09-21T14:39:36.840493+00:00 app[web.1]: jinja2.exceptions.UndefinedError: 'settings' is undefined
2016-09-21T14:39:36.840492+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 408, in getattr
```

Two errors there. The first is something about `github_handle` -- maybe kanru has two users or something integrity related? The second is that it's unhappy about `settings` in the 500.html file.

**Comment by willkg** [comment]
I tried to tackle the 500 issue. It's tricky... The Django TestClient prevents you from testing the unhandled exception `->` http 500 flow. I can't think of how else to test it in an automated way so that I can then fix the template.

@pmac: ^^^ Have you done this before?

**Comment by kanru** [comment]
Yes, I forgot to write that I have two emails bind to my github account.

**Comment by willkg** [comment]
Mmm... I checked the users table and there's a bunch of junk data. I'm not really sure what caused @kanru's problem such that we can't reproduce it. No one else that's tested has hit it so far. I'm thinking maybe we punt on it for now until we know more.

Regarding the junk data, I think we can push off fixing it. It's likely one or two people will encounter issues and we can fix them one at a time by hand in the admin.

The 500 page should get fixed, but I can't figure out how to test it effectively. I'll spin off a new issue for that. I don't think it should block us, either.

Given all that, I'm going to nix the milestone from this for now.

**Comment by willkg** [comment]
We fixed the error page. @pmac and @mythmon debugged this and we're pretty sure the problem is issues with the data which isn't wholly surprising. I think we're just going to fix these one-by-one since it only happens to a small subset of people.

Towards that, I changed the error page last night to point people who hit errors towards getting help with their user account. It's not the most helpful error message, but between that and Sentry, I think we can identify and fix the data problems more quickly.

I went back through Sentry and see errors for the following users:

* @ejregithub
* @mythmon
* @kanru 

I don't see anyone else, but I think some people hit issues before we got Sentry set up, so we just don't know.

I think @mythmon is sorted out.

Does anyone else need help fixing their user account?

**Comment by ejregithub** [comment]
Oh, good, it wasn't operator error
on my part.  I'll (@ejregithub) try again.

Regards,

Eric

**Comment by froydnj** [comment]
I just hit this error.  The error page says "If you hit this error page after logging in with github, please let us know so we can fix your Standup user account."

**Comment by froydnj** [comment]
...but apparently my status was posted despite the server error, so everything is Just Fine?

**Comment by willkg** [comment]
@froydnj You should be fine. The error that I saw was a db connection error which shouldn't happen, but is probably ephemeral. It's not related to this issue.

**Comment by willkg** [comment]
@kanru @froydnj I just pushed out changes that ditch Persona and Github auth in favor of Auth0 which lets you use Github to authenticate or a passwordless email code.

Can you try that out and see if you can log in? If you have any problems, let me know.

**Comment by kanru** [comment]
@willkg 
> Can you try that out and see if you can log in? If you have any problems, let me know.

I tried and could login via Auth0, however it used the wrong email. In the end I use the email based login directly.

**Comment by willkg** [comment]
Seems like @kanru is fine and it's been a while since anyone else has replied, so I think we're all set here.

If anyone is still having problems logging in, please open up a new issue and we'll chase it down. The newly rewritten Auth0 stuff I pushed today should be much better about things.
