### ISSUE TITLE
DisallowedHost: standups.herokuapp.com

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#235]
We're seeing a bunch of these in prod right now:

```
2016-09-23T17:02:59.433657+00:00 app[web.1]: [2016-09-23 17:02:59 +0000] [18] [ERROR] Error handling request /status/36347
2016-09-23T17:02:59.433673+00:00 app[web.1]: Traceback (most recent call last):
2016-09-23T17:02:59.433675+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 108, in get_response
2016-09-23T17:02:59.433675+00:00 app[web.1]:     response = middleware_method(request)
2016-09-23T17:02:59.433676+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/middleware/common.py", line 62, in process_request
2016-09-23T17:02:59.433678+00:00 app[web.1]:     host = request.get_host()
2016-09-23T17:02:59.433679+00:00 app[web.1]:   File "/usr/local/lib/python3.5/dist-packages/django/http/request.py", line 101, in get_host
2016-09-23T17:02:59.433680+00:00 app[web.1]:     raise DisallowedHost(msg)
2016-09-23T17:02:59.433681+00:00 app[web.1]: django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'standups.herokuapp.com'. You may need to add 'standups.herokuapp.com' to ALLOWED_HOSTS.
```

I don't know offhand what's sending people that way. Should we add that to the `ALLOWED_HOSTS`? Any idea what might be sending people to standups.herokuapp.com?

**Comment by willkg** [comment]
I bet we can't change the `ALLOWED_HOSTS` because we need it to match the cert. So I think that's off the table. I'll try to find whoever is using this domain and tell them what's going on.

**Comment by pmac** [comment]
I saw that too and did change `ALLOWED_HOSTS`. I believe it's fine because the DNS for `standups.herokuapp.com` points to a different place that uses Heroku's wildcard cert. We should add a redirect to the real domain though once we get SSL worked out.

**Comment by pmac** [comment]
I don't have any idea why people are using that domain though. Perhaps they just want the SSL?

**Comment by willkg** [comment]
I have no idea, either. I tried to figure out who was using it and failed miserably. I think in order to figure it out, I'd have to log incoming requests and see the user-agent and some other attributes.

Your theory sounds plausible to me.
